services:
  app:
    image: node:19
    ports:
      - 3001:3000
    command: sh -c "npm install && npm run build && node build"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - ORIGIN=https://admin.primerjalnik.si # change this to match your ssh keys
