services:

  # srvus:
  #   image: alpine
  #   working_dir: /
  #   command: sh -c "apk add -u -l openssh-client && until ssh srv.us -R 1:app:3000; do echo Restarting…; done"
  #   volumes:
  #     - .ssh:/root/.ssh #you should have a folder named .ssh with the keys

  app:
    image: node:19
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run build && node build"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - ORIGIN=https://s5hjgvuaesh6peumgmk35kfu54.srv.us # change this to match your ssh keys

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data # this shoudl be a normal pocketbase folder
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
